### ISSUE TITLE
Unknown host exception

### ISSUE THREAD

**Issue by MissingRoberto** [murphjm/JavaPusherClient#4]
Hello, if I execute the code in a java aplication, pusher works, but when I do in an android application, I get this error:

10-17 16:54:25.468: W/System.err(279): java.net.UnknownHostException: ws.pusherapp.com
10-17 16:54:25.478: W/System.err(279):  at java.net.InetAddress.lookupHostByName(InetAddress.java:513)
10-17 16:54:25.478: W/System.err(279):  at java.net.InetAddress.getAllByNameImpl(InetAddress.java:278)
10-17 16:54:25.478: W/System.err(279):  at java.net.InetAddress.getAllByName(InetAddress.java:242)
10-17 16:54:25.478: W/System.err(279):  at java.net.Socket.tryAllAddresses(Socket.java:169)
10-17 16:54:25.488: W/System.err(279):  at java.net.Socket.<init>(Socket.java:258)
10-17 16:54:25.488: W/System.err(279):  at java.net.Socket.<init>(Socket.java:222)
10-17 16:54:25.488: W/System.err(279):  at com.justinschultz.websocket.WebSocketConnection.createSocket(WebSocketConnection.java:228)

Any idea??

**Comment by MissingRoberto** [comment]
My fault, is for the android permission, sorry :)
