### ISSUE TITLE
Java.net.SocketException: Socket closed

### ISSUE THREAD

**Issue by jeremyhahn** [murphjm/JavaPusherClient#5]
Getting this exception when I call Pusher.disconnect(). Am I doing something wrong or is this a bug?

java.net.SocketException: Socket closed
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:150)
    at java.net.SocketInputStream.read(SocketInputStream.java:121)
    at java.net.SocketInputStream.read(SocketInputStream.java:203)
    at com.justinschultz.websocket.WebSocketReceiver.run(WebSocketReceiver.java:47)

**Comment by avaranovich** [comment]
@jeremyhahn I am facing the same issue. Did you figure out why this exception happens?

**Comment by leggetter** [comment]
A bit off topic - but we (Pusher) have a new project ongoing for a Java/Android library that we're going to support and maintain in-house. Maybe @jmschultz plans to maintain this - if so, cool - but if you would consider using another library then there's an in development version available here: https://github.com/leggetter/pusher-java-client

We'd very much appreciate early users testing and submitting feedback, and possibly issues :)

Very simple example app here: https://github.com/leggetter/pusher-android-example

@jmschultz if you are interested and willing to contribute to the new library it would be awesome.
